version: '2'
services:

    dist.front:
        container_name: dist.front
        image: nginx:alpine
        working_dir: '/usr/share/nginx/html'
        environment:
            - HOST=0.0.0.0
        ports:
            - '80:80'
        volumes:
            - ./nuxt/dist:/usr/share/nginx/html
        networks:
            - dist
        command: sh -c 'echo "server {listen 80;server_name localhost;location / {root /usr/share/nginx/html;index index.html index.htm;absolute_redirect off;}}" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'


networks:
    dist:
