version: '3'
services:
  #strapi:
  #  build:
  #    context: ./app
  #    dockerfile: strapi.Dockerfile
  #  environment:
  #    APP_NAME: app
  #    DATABASE_CLIENT: mysql
  #    DATABASE_HOST: mysql
  #    DATABASE_PORT: 3306
  #    DATABASE_NAME: strapi
  #    DATABASE_USERNAME: strapi
  #    DATABASE_PASSWORD: strapi
  #    DATABASE_SSL: 'false'
  #  volumes:
  #    - ./app:/srv/app
  #  ports:
  #    - '1337:1337'
  #  depends_on:
  #    - mysql
  
  strapi:
    image: strapi/strapi
    working_dir: /srv/app
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    command: bash -c 'npm set unsafe-perm=true && yarn install  && yarn run develop'

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
  
  front.nuxt:
        container_name: ${WUXT_NUXT_CONTAINER:-front.nuxt-site}
        image: node:12.16.3
        working_dir: '/var/www/app'
        environment:
            - HOST=0.0.0.0
            - WUXT_WP_CONTAINER=${WUXT_WP_CONTAINER:-wp.wuxt}
            - WUXT_PORT_BACKEND=${WUXT_PORT_BACKEND:-3080}
        ports:
            - '${WUXT_PORT_FRONTEND-3000}:3000'
        volumes:
            - ./nuxt:/var/www/app
        command: bash -c 'yarn config set "strict-ssl" false && yarn install && WUXT_PORT_BACKEND=${WUXT_PORT_BACKEND:-3080} yarn dev'
        

#  front:
#    build: ./nuxt
#    image: nodejs-nuxt:1.0.1
#    working_dir: /nuxt
#    stdin_open: true        #comment out for build.target:prod
#    tty: true               #comment out for build.target:prod
#    environment:
#      - HOST=127.0.0.1
#      - NODE_ENV=development
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./nuxt:/nuxt
#      - node_modules:/nuxt/node_modules
#volumes:
#   
#  node_modules:

  #
  #  command: bash -c 'npm install &&  npm run generate && npm run dev'
    
    