version: '3'
services:
  nuxt-strapi:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - ./:/srv/nuxt
    